/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mengelolabuku;
import java.awt.HeadlessException;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import mengelolabuku.koneksi;
import javax.swing.table.*;
/**
 *
 * @author pitria
 */
public class interfacemengelolabuku extends javax.swing.JFrame {

    /**
     * Creates new form interfacemengelolabuku
     */
    Connection koneksi = mengelolabuku.koneksi.getKoneksi();
    Statement tokobuku; 
    ResultSet databuku; 
    Boolean ketemu = false;
    public interfacemengelolabuku() {
        initComponents();
    }
     //mengkosongkan setelah diInput
    private void kosong() {
        inputjudul.setText("");
        inputpenulis.setText("");
        inputharga.setText("");
        inputstok.setText("");

        ButtonTambah.setText("Simpan");
//        btnEdit.setEnabled(false);
    }
    
     public void Tampilkanbuku() {
        try {
            tokobuku = koneksi.createStatement();
            databuku = tokobuku.executeQuery("SELECT * FROM data_buku");

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Judul");
            model.addColumn("Penulis");
            model.addColumn("Harga");
            model.addColumn("Stok");

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            while (databuku.next()) {
                Object[] data = {
                    databuku.getString("judul"),
                    databuku.getString("penulis"),
                    databuku.getString("harga"),
                    databuku.getString("stok"),
                };
                model.addRow(data);
                Tablemengelolabuku.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada Kesalahan " + e.getMessage());
        }
    }
     private void Caribuku() {
        try {
            tokobuku = koneksi.createStatement();
            databuku = tokobuku.executeQuery("SELECT * FROM data_buku WHERE judul LIKE '%" +  txt_cari.getText() + "% '||"
                    + "penulis LIKE '%" +  txt_cari.getText() + "%' ||  "
                    + "harga LIKE '%" +  txt_cari.getText() + "%' || "
                    + "stok LIKE '%" +  txt_cari.getText() + "%'");

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Judul");
            model.addColumn("Penulis");
            model.addColumn("Harga");
            model.addColumn("Stok");

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            while (databuku.next()) {
                Object[] data = {
                    databuku.getString("judul"),
                    databuku.getString("penulis"),
                    databuku.getString("harga"),
                    databuku.getString("stok"),
                };
                model.addRow(data);
                Tablemengelolabuku.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada Kesalahan " + e.getMessage());
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_tambah = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputjudul = new javax.swing.JTextField();
        inputpenulis = new javax.swing.JTextField();
        inputstok = new javax.swing.JTextField();
        inputharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jScrollPanel = new javax.swing.JScrollPane();
        Tablemengelolabuku = new javax.swing.JTable();
        ButtonTambah = new javax.swing.JButton();
        Buttondelete = new javax.swing.JButton();
        Buttonbatal = new javax.swing.JButton();
        jLabelbuku = new javax.swing.JLabel();

        btn_tambah.setText("tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_delete.setText("delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("judul");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Penulis");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Harga");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Stok");

        inputjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputjudulActionPerformed(evt);
            }
        });

        inputpenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpenulisActionPerformed(evt);
            }
        });

        inputstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputstokActionPerformed(evt);
            }
        });

        inputharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputhargaActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari Data :");

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
        });

        Tablemengelolabuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Judul", "Penulis", "Harga", "Stok"
            }
        ));
        Tablemengelolabuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablemengelolabukuMouseClicked(evt);
            }
        });
        jScrollPanel.setViewportView(Tablemengelolabuku);

        ButtonTambah.setText("Tambah");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        Buttondelete.setText("Delete");

        Buttonbatal.setText("batal");
        Buttonbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonbatalActionPerformed(evt);
            }
        });

        jLabelbuku.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelbuku.setText("Daftar Buku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputjudul, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(inputstok, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputharga, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputpenulis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ButtonTambah)
                        .addGap(27, 27, 27)
                        .addComponent(Buttondelete)
                        .addGap(18, 18, 18)
                        .addComponent(Buttonbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabelbuku)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelbuku)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTambah)
                    .addComponent(Buttondelete)
                    .addComponent(Buttonbatal))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                      
    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void inputjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputjudulActionPerformed

    private void inputpenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputpenulisActionPerformed

    private void inputhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputhargaActionPerformed

    private void inputstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputstokActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if (inputjudul.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih buku yang akan di hapus");
        } else {
            int jawab = JOptionPane.showConfirmDialog(null, "Buku Ini akan dihapus, lanjutkan?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (jawab == 0) {
                try {
                    tokobuku = koneksi.createStatement();
                    String sql = "DELETE FROM data_buku WHERE judul = '" + inputjudul.getText() + "'";
                    tokobuku.executeUpdate(sql);

                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    kosong();
                    Tampilkanbuku();

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Buku Tidak Dapat Dihapus" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_txt_cariKeyPressed

    private void TablemengelolabukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablemengelolabukuMouseClicked
        // TODO add your handling code here:
        int baris = Tablemengelolabuku.rowAtPoint(evt.getPoint());
        String id =Tablemengelolabuku.getValueAt(baris, 1).toString();
        inputjudul.setText(id);
        String nama = Tablemengelolabuku.getValueAt(baris,2).toString();
       

        String jr = Tablemengelolabuku.getValueAt(baris, 3).toString();
       
        String quantity=Tablemengelolabuku.getValueAt(baris, 4).toString();
        
        String price = Tablemengelolabuku.getValueAt(baris, 5).toString();
       
    }//GEN-LAST:event_TablemengelolabukuMouseClicked

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
         try {
            // simpan data
            tokobuku = koneksi.createStatement();
            if (inputjudul.getText().equals("")
                || inputpenulis.getText().equals("")
                || inputharga.getText().equals("")
                || inputstok.getText().equals("")
                ) {
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong", "Validasi data", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            
            if (ButtonTambah.getText() == "Tambah") {
                String cek = "SELECT * FROM data_buku WHERE judul = '" + inputjudul.getText() + "'";
                databuku = tokobuku.executeQuery(cek);
                if (databuku.next()) {
                    JOptionPane.showMessageDialog(null, "Upss.... ID ini Sudah Terdaftar");
                } else {
                    String judul = inputjudul.getText();
                    String penulis = inputpenulis.getText();
                    double harga = Double.parseDouble(inputharga.getText());
                    int stok = Integer.parseInt(inputstok.getText());

                    String sql = "INSERT INTO data_buku (judul, penulis, harga, stok) VALUES ('"
                        + judul + "', '"
                        + penulis + "', "
                        + harga + ", "
                        + stok + ")";
                    tokobuku.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Simpan Data Berhasil");
                    kosong();
                    Tampilkanbuku();
                }
            } else {
                //aksi ubah data
                String judul = inputjudul.getText();
                String penulis = inputpenulis.getText();
                double harga = Double.parseDouble(inputharga.getText());
                int stok = Integer.parseInt(inputstok.getText());
                    
               String sql = "UPDATE data_buku SET penulis = '" + penulis + "', harga = "
                + harga + ", stok = "
                + stok + " WHERE judul = '"
                + judul + "'";

                // Eksekusi query
                int rowsUpdated = tokobuku.executeUpdate(sql);
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Edit Data Berhasil");
                } else {
                    JOptionPane.showMessageDialog(null, "Judul Buku tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
                }
                

                kosong();
                Tampilkanbuku();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tambah Buku Gagal " + e.getMessage());
        }

    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonbatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfacemengelolabuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfacemengelolabuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfacemengelolabuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfacemengelolabuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfacemengelolabuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JButton Buttonbatal;
    private javax.swing.JButton Buttondelete;
    private javax.swing.JTable Tablemengelolabuku;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JTextField inputharga;
    private javax.swing.JTextField inputjudul;
    private javax.swing.JTextField inputpenulis;
    private javax.swing.JTextField inputstok;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelbuku;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
